apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redis-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: redis-operator
  source: community-operators
  sourceNamespace: openshift-marketplace

