kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hotfix-redis-operator-permissions
subjects:
  - kind: ServiceAccount
    name: redis-operator
    namespace: redis-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hotfix-redis-operator-permissions
