kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hotfix-redis-operator-permissions
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - redis.redis.opstreelabs.in
    resources:
      - redisreplications
      - redissentinels
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - redis.redis.opstreelabs.in
    resources:
      - redisclusters/status
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
